"""
coroforge branding: where the logo files live, and the one call that puts
the logo in the sidebar.

The images in app/assets/ are generated by app/assets/make_logo.py (pixel
art, so the SVGs stay crisp at any size). Rerun that script after changing
the design; nothing here needs to change unless a file is renamed.
"""
from pathlib import Path

import streamlit as st

ASSETS_DIR = Path(__file__).resolve().parents[1] / "assets"

# Browser-tab icon, for st.set_page_config(page_icon=...) on every page.
PAGE_ICON = str(ASSETS_DIR / "coroforge_icon.png")
# Full lockup with the tagline - shown large on the Home page.
LOGO_FULL = str(ASSETS_DIR / "coroforge_logo.svg")
# Icon + wordmark without the tagline - st.logo caps the height at 32 px,
# where the tagline would be unreadable.
LOGO_SIDEBAR = str(ASSETS_DIR / "coroforge_logo_sidebar.png")
# Square icon shown in the top-left corner when the sidebar is collapsed.
LOGO_ICON = str(ASSETS_DIR / "coroforge_icon.png")


def render_sidebar_logo() -> None:
    """
    Puts the coroforge logo at the top of the sidebar (and the square icon in
    the top-left corner when the sidebar is collapsed). Called from
    app.state.init_state(), so every page gets it without its own call.
    """
    st.logo(LOGO_SIDEBAR, size="large", icon_image=LOGO_ICON)
